// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientHealth.DataBase;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203133454_NotificationsSeedUpdate")]
    partial class NotificationsSeedUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApi.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regularity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80b9a465-e7ae-41e6-8b79-684d30a19340"),
                            Date = new DateTime(2023, 12, 4, 15, 34, 54, 106, DateTimeKind.Local).AddTicks(4812),
                            Description = "Don't forget your appointment tomorrow at 10 AM.",
                            Doctor = "Dr. Smith",
                            Duration = 30,
                            Label = "Appointment Reminder",
                            Regularity = "Once",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22ad025a-28d9-42ed-895c-bdbe66c34571"),
                            Date = new DateTime(2023, 12, 3, 21, 34, 54, 106, DateTimeKind.Local).AddTicks(4855),
                            Description = "Time to take your medication.",
                            Doctor = "Dr. Jones",
                            Duration = 0,
                            Label = "Medication Reminder",
                            Regularity = "Daily",
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8e346e53-2937-4a3e-af60-50070f47e6d7"),
                            Date = new DateTime(2023, 12, 5, 15, 34, 54, 106, DateTimeKind.Local).AddTicks(4859),
                            Description = "Your recent lab results are ready for review.",
                            Doctor = "Dr. Green",
                            Duration = 0,
                            Label = "Lab Results",
                            Regularity = "Once",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a38d9124-0915-4323-aa6b-a671e481832f"),
                            Date = new DateTime(2023, 12, 10, 15, 34, 54, 106, DateTimeKind.Local).AddTicks(4864),
                            Description = "Remember to schedule your follow-up appointment.",
                            Doctor = "Dr. White",
                            Duration = 0,
                            Label = "Follow-up Reminder",
                            Regularity = "Once",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("9c61f6ea-4a26-4837-adbd-81cd349f62f1"),
                            Date = new DateTime(2023, 12, 6, 15, 34, 54, 106, DateTimeKind.Local).AddTicks(4868),
                            Description = "Check out the latest health tips on our website.",
                            Duration = 0,
                            Label = "Health Tips",
                            Regularity = "Weekly",
                            Status = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("WebApi.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
